# Uncomment this line to define a global platform for your project
 
# platform :ios, '8.0'
 
use_frameworks!

target 'OneSunChat' do

pod 'SnapKit'

pod 'SVProgressHUD'

end

target 'OneSunChatTests' do

end

target 'OneSunChatUITests' do

end

